name: github actions demo name
run-name: testing github actions run-name
on: [push]
jobs:
  basic_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job basic_workflow is executing as part of new workflow"
      
