name: myrepo var test
run-name: myrepo var test
on: [push]
env:
  MYREPO_VAR: ${{ vars.MYREPO_VAR }}
jobs:
  use_myrepo_var:
    runs-on: ubuntu-latest
    steps:
      -run: echo "This is my repo variable $MYREPO_VAR"
      
