name: Variables Demo
run-name: Testing env variable
on: [push]
env:
  owner-name: Lance
jobs:
  use_env_var:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job use_env_var is executing as part of new workflow - from $owner-name"
      
